version: "3.7"
services:
    php:
        build:
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www

    mysql:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./docker/volume/mysql:/var/lib/mysql

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - './:/var/www'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 9090:80
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
