name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: u791011727
        host: 45.84.207.193
        port: 65002
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /public_html && ./server_deploy.sh'
      
