name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: u791011727_zoo_shop_user
          MYSQL_PASSWORD: 7HqfBV~%e(4R.(!
          MYSQL_DATABASE: u791011727_zoo_shop
          MYSQL_ROOT_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        php --version
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        chmod -R 777 storage bootstrap/cache
    - name: Boot Laravel application
      run: php artisan --version
    - name: Execute migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: localhost
        DB_PORT: 3306
        DB_DATABASE: u791011727_zoo_shop
        DB_USERNAME: u791011727_zoo_shop_user
        DB_PASSWORD: 7HqfBV~%e(4R.(!
      run: |
        php artisan migrate --force
      
