name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          SOURCE: "/domains/zoo-shop-api.online/public_html/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: "/"
          SCRIPT_BEFORE: |
            whoami
          SCRIPT_AFTER: |
            chmod u+x server_deploy.sh && ./server_deploy.sh
      
