name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Deploy to production
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: 45.84.207.193
        port: 65002
        username: u791011727
        password: ${{ secrets.SSH_PASSWORD }}
        scp_source: 'cd /public_html && ./server_deploy.sh'
        scp_target: ~/public_html
        before_script: |
          df -h
        after_script: |
          whoami
      
