name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "zoo-shop-application-packages"
  EB_APPLICATION_NAME       : "ZooShop"
  EB_ENVIRONTMENT_NAME      : "ZooShop-env"
  DEPLOY_PACKAGE_NAME       : "laravel_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on: 
  push:
    branches:
      - main
      
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
        
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
